@startuml

' Define the components
node "Server" as API {
    node "Backend Container\n (Docker)" as DockerImage {
        component "FastAPI gateway\nLoad Balancer\nReverse Proxy" as FastAPIApp
        component "Text To Speech Service" as TTSService
        component "Transcript Service" as TranscriptService
        component "Authentication Service" as AuthService
    }
    database "In Memory Cache\n (Redis)" as Cache

}

collections "Web Clients" as WebClient


FastAPIApp -down-> TranscriptService : Uses
FastAPIApp -down-> AuthService : Uses

TranscriptService -down-> TTSService : Uses
TranscriptService -down-> Cache : Uses

WebClient "*" -down-> "1" FastAPIApp : <<HTTP>> Streaming API Requests (WebSocket)

@enduml